name: sanademy
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.6
  dio: ^5.4.0
  connectivity_plus: ^5.0.2
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.9
  get_storage: ^2.1.1
  intl_phone_field: ^3.2.0
  octo_image: ^2.0.0
  pinput: ^4.0.0
  carousel_slider: ^4.2.1
  syncfusion_flutter_sliders: ^25.1.39
  video_player: ^2.8.5
  audio_waveforms: ^1.0.5
  path_provider: ^2.0.11
  flutter_file_downloader: ^1.2.1
  connectivity: ^3.0.6
  image_picker:
  intl: ^0.19.0
  flutter_html:
  youtube_player_flutter: ^9.0.1
  chewie: ^1.8.5
#  fastpay_merchant: ^1.1.1
  url_launcher: ^6.3.1
  firebase_auth: ^4.10.0
  firebase_core:
  firebase_messaging: ^14.7.19
  flutter_local_notifications: ^17.1.2
#  device_info_plus:
  flutter_native_splash:


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/

  fonts:
    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand-Regular.ttf
          weight: 400
        - asset: assets/fonts/Quicksand-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Quicksand-Bold.ttf
          weight: 700
        - asset: assets/fonts/Metropolis-Regular.otf
          weight: 400
        - asset: assets/fonts/Metropolis-SemiBold.otf
          weight: 600
        - asset: assets/fonts/Metropolis-Bold.otf
          weight: 700

